version: '3.7'

services:
  db:
    build: db
    container_name: postgres-db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    networks:
      - app-network

  springboot-app:
    build: java/simple-api-student-main
    container_name : springboot-app-container
    environment:
      - URL=db:5432
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

    networks:
      - app-network
    depends_on:
      - db
      
  my-apache-server:
    build: proxy
    container_name: my-apache-server-container
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - springboot-app

networks:
  app-network:
    driver: bridge 