- name: Run HTTPD
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: httpd
    image: raghad2000/tp-devops-httpd:latest
    networks:
      - name: "{{ DOCKER_NETWORK }}" 
    ports:
      - 8080:80
    # env:
    #   API_URL: "{{ API_CONTAINER }}"
    recreate: true
    pull: true